=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/src/xml/rdn.dtd
<!--

  Proximity Relational Dependency Network (RDN) DTD
  Version: 1.0

  Used to group RPT files and user item maps into a single file that is used to
  graph the RDN.

  Part of the open-source Proximity system
  (see LICENSE for copyright and license information).
  -->

<!ELEMENT rdn (rpt-files, item-maps*)>

<!ELEMENT rpt-files (file+)>
<!ELEMENT file (#PCDATA)>

<!ELEMENT item-maps (map+)>
<!ELEMENT map (from, to+)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/tutorial/examples/1d-clusters-rdn.xml
<!DOCTYPE rdn SYSTEM "rdn.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for
     copyright and license information).
-->

<rdn>
    <rpt-files>
        <file>ProxWebKB_RPTforRDN.xml</file>
    </rpt-files>
    <item-maps>
        <map>
            <from>core_page</from>
            <to>linked_to_page</to>
        </map>
        <map>
            <from>core_page</from>
            <to>linked_from_page</to>
        </map>
    </item-maps>
</rdn>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/rdnview/t5-rdn.xml
<!DOCTYPE rdn SYSTEM "rdn.dtd">

<!--
    Part of the open-source Proximity system
   (see LICENSE for copyright and license information).
-->
<rdn>
    <rpt-files>
        <file>t5-actor-gender.xml</file>
        <file>t5-actor-hasAward.xml</file>
        <file>t5-movie-genre.xml</file>
        <file>t5-movie-isOWBlockbuster.xml</file>
    </rpt-files>
    <item-maps>
        <map>
            <from>movie</from>
            <to>actor_movie</to>
        </map>
    </item-maps>
</rdn>
