=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/rdnview/rpt2.dtd
<!--

  Proximity Relational Probability Tree (RPT) DTD
  Version: 2.0

  Part of the open-source Proximity system
  (see LICENSE for copyright and license information).

  -->

<!-- rpt -->

<!ELEMENT rpt2 (class-label, rpt-body)>


<!-- class-label -->

<!ELEMENT class-label (source) >
<!ELEMENT source (source-class, data-type, is-continuous, is-single-value, source-elements) >
<!ELEMENT source-class (#PCDATA)>
<!ELEMENT data-type (#PCDATA)>
<!ELEMENT is-continuous (#PCDATA)>
<!ELEMENT is-single-value (#PCDATA)>
<!ELEMENT source-elements ( (item-name)?, (attr-name)?, (temporal-col)? , (from)?, (to)?, (interval-min)?, (interval-max)?, (core-time-source)?, (related-time-source)?) >
<!ELEMENT item-name (#PCDATA)>
<!ELEMENT attr-name (#PCDATA)>
<!ELEMENT interval-min (#PCDATA)>
<!ELEMENT interval-max (#PCDATA)>
<!ELEMENT temporal-col (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT core-time-source ( (item-name)?, (attr-name)?) >
<!ELEMENT related-time-source ( (item-name)?, (attr-name)?) >

<!-- rpt-body -->
<!ELEMENT rpt-body (node) >
<!ELEMENT yes-branch (node) >
<!ELEMENT no-branch (node) >
<!ELEMENT node (class-label-distr, (split)?, (yes-branch)?, (no-branch)?) >

<!ELEMENT class-label-distr (distr-class, (class-label-info)*) >
<!ELEMENT distr-class (#PCDATA)>
<!ELEMENT class-label-info (#PCDATA) >
<!ATTLIST class-label-info class CDATA #REQUIRED>
<!ATTLIST class-label-info count CDATA #REQUIRED>

<!ELEMENT split (feature-setting)>
<!ELEMENT feature-setting (fs-class, source, aggregator, threshold, fs-elements) >
<!ELEMENT fs-class (#PCDATA)>
<!ELEMENT threshold (#PCDATA)>
<!ELEMENT aggregator (aggregator-class) >
<!ELEMENT aggregator-class (#PCDATA)>
<!ELEMENT fs-elements (value?) >
<!ELEMENT value (#PCDATA)>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/rdnview/t6-movie-genre.xml
<!DOCTYPE rpt2 SYSTEM "rpt2.dtd">
<!-- Created by Proximity 4.2 -->

<rpt2>
    <class-label>
        <source>
            <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
            <data-type>str</data-type>
            <is-continuous>false</is-continuous>
            <is-single-value>false</is-single-value>
            <source-elements>
                <item-name>movie</item-name>
                <attr-name>genre</attr-name>
            </source-elements>
        </source>
    </class-label>
    <rpt-body>
        <node>
            <class-label-distr>
                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                <class-label-info class="0" count="166"/>
                <class-label-info class="1" count="144"/>
            </class-label-distr>
            <split>
                <feature-setting>
                    <fs-class>kdl.prox.model2.rpt.featuresettings.ValueFilteredFeatureSetting</fs-class>
                    <source>
                        <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
                        <data-type>int</data-type>
                        <is-continuous>false</is-continuous>
                        <is-single-value>false</is-single-value>
                        <source-elements>
                            <item-name>actorIn</item-name>
                            <attr-name>salary</attr-name>
                        </source-elements>
                    </source>
                    <aggregator>
                        <aggregator-class>kdl.prox.model2.rpt.aggregators.CountAggregator</aggregator-class>
                    </aggregator>
                    <threshold>3</threshold>
                    <fs-elements>
                        <value>High</value>
                    </fs-elements>
                </feature-setting>
            </split>
            <yes-branch>
                <node>
                    <class-label-distr>
                        <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                        <class-label-info class="0" count="26"/>
                        <class-label-info class="1" count="40"/>
                    </class-label-distr>
                </node>
            </yes-branch>
            <no-branch>
                <node>
                    <class-label-distr>
                        <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                        <class-label-info class="0" count="124"/>
                        <class-label-info class="1" count="7"/>
                    </class-label-distr>
                </node>
            </no-branch>
        </node>
    </rpt-body>
</rpt2>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/rdnview/t7-book_role.xml
<!DOCTYPE rpt2 SYSTEM "rpt2.dtd">
<!-- Created by Proximity 4.2 -->

<rpt2>
    <class-label>
        <source>
            <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
            <data-type>str</data-type>
            <is-continuous>false</is-continuous>
            <is-single-value>true</is-single-value>
            <source-elements>
                <item-name>journal_book</item-name>
                <attr-name>book_role</attr-name>
            </source-elements>
        </source>
    </class-label>
    <rpt-body>
        <node>
            <class-label-distr>
                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                <class-label-info class="CONF" count="266.0"/>
                <class-label-info class="SYMP" count="18.0"/>
                <class-label-info class="WORK" count="81.0"/>
            </class-label-distr>
            <split>
                <feature-setting>
                    <fs-class>kdl.prox.model2.rpt.featuresettings.UnfilteredFeatureSetting</fs-class>
                    <source>
                        <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
                        <data-type>int</data-type>
                        <is-continuous>false</is-continuous>
                        <is-single-value>false</is-single-value>
                        <source-elements>
                            <item-name>journal_book</item-name>
                            <attr-name>book_role</attr-name>
                        </source-elements>
                    </source>
                    <aggregator>
                        <aggregator-class>kdl.prox.model2.rpt.aggregators.ModeAggregator</aggregator-class>
                    </aggregator>
                    <threshold>WORK</threshold>
                    <fs-elements>
                    </fs-elements>
                </feature-setting>
            </split>
            <yes-branch>
                <node>
                    <class-label-distr>
                        <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                        <class-label-info class="CONF" count="266.0"/>
                        <class-label-info class="SYMP" count="18.0"/>
                        <class-label-info class="WORK" count="81.0"/>
                    </class-label-distr>
                    <split>
                        <feature-setting>
                            <fs-class>kdl.prox.model2.rpt.featuresettings.UnfilteredFeatureSetting</fs-class>
                            <source>
                                <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
                                <data-type>int</data-type>
                                <is-continuous>false</is-continuous>
                                <is-single-value>false</is-single-value>
                                <source-elements>
                                    <item-name>journal_book</item-name>
                                    <attr-name>book_role</attr-name>
                                </source-elements>
                            </source>
                            <aggregator>
                                <aggregator-class>kdl.prox.model2.rpt.aggregators.ModeAggregator</aggregator-class>
                            </aggregator>
                            <threshold>SYMP</threshold>
                            <fs-elements>
                            </fs-elements>
                        </feature-setting>
                    </split>
                    <yes-branch>
                        <node>
                            <class-label-distr>
                                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                                <class-label-info class="CONF" count="266.0"/>
                                <class-label-info class="SYMP" count="18.0"/>
                                <class-label-info class="WORK" count="81.0"/>
                            </class-label-distr>
                        </node>
                    </yes-branch>
                    <no-branch>
                        <node>
                            <class-label-distr>
                                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                                <class-label-info class="CONF" count="266.0"/>
                                <class-label-info class="SYMP" count="18.0"/>
                                <class-label-info class="WORK" count="81.0"/>
                            </class-label-distr>
                        </node>
                    </no-branch>
                </node>
            </yes-branch>
            <no-branch>
                <node>
                    <class-label-distr>
                        <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                        <class-label-info class="CONF" count="266.0"/>
                        <class-label-info class="SYMP" count="18.0"/>
                        <class-label-info class="WORK" count="81.0"/>
                    </class-label-distr>
                </node>
            </no-branch>
        </node>
    </rpt-body>
</rpt2>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/rdnview/t6-actor-gender.xml
<!DOCTYPE rpt2 SYSTEM "rpt2.dtd">
<!-- Created by Proximity 4.2 -->

<rpt2>
    <class-label>
        <source>
            <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
            <data-type>str</data-type>
            <is-continuous>false</is-continuous>
            <is-single-value>false</is-single-value>
            <source-elements>
                <item-name>actorIn</item-name>
                <attr-name>salary</attr-name>
            </source-elements>
        </source>
    </class-label>
    <rpt-body>
        <node>
            <class-label-distr>
                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                <class-label-info class="high" count="772"/>
                <class-label-info class="low" count="610"/>
            </class-label-distr>
        </node>
    </rpt-body>
</rpt2>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/tutorial/examples/s-class-rpt.xml
<!DOCTYPE rpt2 SYSTEM "rpt2.dtd">
<!-- Created by Proximity 4.2 -->

<rpt2>
    <class-label>
        <source>
            <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
            <data-type>str</data-type>
            <is-continuous>false</is-continuous>
            <is-single-value>false</is-single-value>
            <source-elements>
                <item-name>S</item-name>
                <attr-name>class</attr-name>
            </source-elements>
        </source>
    </class-label>
    <rpt-body>
        <node>
            <class-label-distr>
                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                <class-label-info class="+" count="50.0"/>
                <class-label-info class="-" count="50.0"/>
            </class-label-distr>
            <split>
                <feature-setting>
                    <fs-class>kdl.prox.model2.rpt.featuresettings.UnfilteredFeatureSetting</fs-class>
                    <source>
                        <source-class>kdl.prox.model2.common.sources.ItemSource</source-class>
                        <data-type>str</data-type>
                        <is-continuous>false</is-continuous>
                        <is-single-value>false</is-single-value>
                        <source-elements>
                            <item-name>linked1_T</item-name>
                        </source-elements>
                    </source>
                    <aggregator>
                        <aggregator-class>kdl.prox.model2.rpt.aggregators.DegreeAggregator</aggregator-class>
                    </aggregator>
                    <threshold>5</threshold>
                    <fs-elements/>
                </feature-setting>
            </split>
            <yes-branch>
                <node>
                    <class-label-distr>
                        <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                        <class-label-info class="+" count="95.0"/>
                        <class-label-info class="-" count="5.0"/>
                    </class-label-distr>
                </node>
            </yes-branch>
            <no-branch>
                <node>
                    <class-label-distr>
                        <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                        <class-label-info class="+" count="50.0"/>
                        <class-label-info class="-" count="50.0"/>
                    </class-label-distr>
                    <split>
                        <feature-setting>
                            <fs-class>kdl.prox.model2.rpt.featuresettings.UnfilteredFeatureSetting</fs-class>
                            <source>
                                <source-class>kdl.prox.model2.common.sources.ItemSource</source-class>
                                <data-type>str</data-type>
                                <is-continuous>false</is-continuous>
                                <is-single-value>false</is-single-value>
                                <source-elements>
                                    <item-name>linked1_T</item-name>
                                </source-elements>
                            </source>
                            <aggregator>
                                <aggregator-class>kdl.prox.model2.rpt.aggregators.DegreeAggregator</aggregator-class>
                            </aggregator>
                            <threshold>2</threshold>
                            <fs-elements/>
                        </feature-setting>
                    </split>
                    <yes-branch>
                        <node>
                            <class-label-distr>
                                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                                <class-label-info class="+" count="15.0"/>
                                <class-label-info class="-" count="85.0"/>
                            </class-label-distr>
                        </node>
                    </yes-branch>
                    <no-branch>
                        <node>
                            <class-label-distr>
                                <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
                                <class-label-info class="+" count="5.0"/>
                                <class-label-info class="-" count="95.0"/>
                            </class-label-distr>
                        </node>
                    </no-branch>
                </node>
            </no-branch>
        </node>
    </rpt-body>
</rpt2>
