=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/family/data/families/family_4/graph-query.dtd
<!--
$Id: graph-query.dtd 2733 2006-09-11 21:33:59Z schapira $

Part of the open-source Proximity system
(see LICENSE for copyright and license information).

Proximity Graph Query DTD. Does not support the following:
    o updates
    o atomic_constraint -> ... | const_term comp_op const_term
    o cond_term -> ... | agg_op (attr_name) | ...
    o annotation -> [counter_var := annot_limits] | ...
-->


<!-- graph-query -->

<!ELEMENT graph-query (description?, query-body, editor-data?)>
<!ATTLIST graph-query name CDATA #REQUIRED>


<!-- description -->
<!ELEMENT description (#PCDATA)>


<!-- query-body -->

<!ELEMENT query-body (vertex, (edge | vertex)*, subquery*, constraint?, add-link*, cached*)>
<!ELEMENT subquery (vertex, (edge | vertex)*, subquery*, numeric-annotation)>

<!ELEMENT vertex (condition?, numeric-annotation?)>
<!ATTLIST vertex name CDATA #REQUIRED>

<!ELEMENT edge (vertex1, vertex2, directed, condition?, numeric-annotation?)>
<!ATTLIST edge name CDATA #REQUIRED>
<!ELEMENT vertex1 (#PCDATA)>	<!-- NB: direction is FROM 1 TO 2! -->
<!ELEMENT vertex2 (#PCDATA)>
<!ELEMENT directed (#PCDATA)>	<!-- possible values: "true", "false" -->

<!ELEMENT numeric-annotation (min, max?)>	<!-- min and max are whole numbers, and min <= max. valid combinations: [i..j], [i..], or [i] -->
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>


<!ENTITY % dnf "(or | and | not | test)">	<!-- disjunctive normal form -->
<!-- constraints should only test between pairs items
     We use DNF in the DTD for consistency, but in reality only <AND>s can be used in constraints
     also, no constrainsts involving annotated vertices are allowed.
 -->
<!ELEMENT constraint %dnf;>
<!ELEMENT condition %dnf;>		<!-- conditions should only compare attribute names and values, or existence of an attribute name -->

<!ENTITY % and-body "not | test">
<!ELEMENT or (and | %and-body;)+>
<!ELEMENT and (%and-body;)+>
<!ELEMENT not (test)>

<!-- test operands should be consistent:
  for constraints: two edge-names, or two vertex-names
  for conditions - operators:
       "eq", "ge", "le", "ne" : an attribute-name and a value (binary operators), or two items
       "exists"               :  an attribute name (unary operator)
 -->
<!ENTITY % operand "(attribute-name | value | item)">
<!ELEMENT test (operator, %operand;, (%operand;)?)>
<!ELEMENT operator (#PCDATA)>	<!-- possible values: "eq", "ge", "gt", "le", "lt", "ne", "exists" -->
<!ELEMENT attribute-name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT item (item-name, (attribute-name | id))>  <!-- for constraints -->
<!ELEMENT item-name (#PCDATA)>
<!ELEMENT id EMPTY>


<!-- editor-data
This is an optional element that contains information specific to the QGraph
editor (more specifically, vertex layout information). We would have preferred
to save the layout in separate files, but decided such a solution would impose
an undue burden on users.
 -->
<!ELEMENT editor-data (vertex-location+)>

<!ELEMENT vertex-location EMPTY>
<!ATTLIST vertex-location name CDATA #REQUIRED>
<!ATTLIST vertex-location x CDATA #REQUIRED>
<!ATTLIST vertex-location y CDATA #REQUIRED>


<!ELEMENT add-link (vertex1, vertex2)>
<!ATTLIST add-link attrname CDATA #REQUIRED>
<!ATTLIST add-link attrval CDATA #REQUIRED>

<!ELEMENT cached EMPTY >
<!ATTLIST cached item CDATA #REQUIRED>
<!ATTLIST cached container CDATA #REQUIRED>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Cond_DB03_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Cond_DB03_Q01">
  <description>Condition testing missing values</description>
  <query-body>
    <vertex name="book">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>book</value>
        </test>
      </condition>
    </vertex>
    <vertex name="movie">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ReleaseType</attribute-name>
          <value>theater</value>
        </test>
      </condition>
    </vertex>
    <edge name="adapted-to">
      <vertex1>book</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>LinkType</attribute-name>
          <value>adapted-to</value>
        </test>
      </condition>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="book" x="109.0" y="144.0" />
    <vertex-location name="movie" x="351.0" y="50.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/SubQ_DB01_Q02.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="SubQ_DB01_Q02">
  <description>Subquery box removed</description>
  <query-body>
    <vertex name="director">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>Director</value>
        </test>
      </condition>
    </vertex>
    <vertex name="movie">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>Movie</value>
        </test>
      </condition>
    </vertex>
    <vertex name="actor">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>Actor</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <edge name="directed">
      <vertex1>director</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <edge name="acted-in">
      <vertex1>actor</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="director" x="28.0" y="110.0" />
    <vertex-location name="movie" x="258.0" y="111.0" />
    <vertex-location name="actor" x="504.0" y="110.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/cookbook/examples/DBManip_AttrsFromData_Query.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for
     copyright and license information). -->

<graph-query name="studio-clusters">
  <description>Finds, for each studio, its movies and associated actors and directors</description>
  <query-body>
    <vertex name="studio">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>obj_type</attribute-name>
          <value>Studio</value>
        </test>
      </condition>
    </vertex>
    <edge name="produced">
      <vertex1>studio</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>link_type</attribute-name>
          <value>Produced</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <subquery>
      <vertex name="actor">
        <condition>
          <test>
            <operator>eq</operator>
            <attribute-name>obj_type</attribute-name>
            <value>Actor</value>
          </test>
        </condition>
        <numeric-annotation>
          <min>0</min>
        </numeric-annotation>
      </vertex>
      <vertex name="movie">
        <condition>
          <test>
            <operator>eq</operator>
            <attribute-name>obj_type</attribute-name>
            <value>Movie</value>
          </test>
        </condition>
      </vertex>
      <vertex name="director">
        <condition>
          <test>
            <operator>eq</operator>
            <attribute-name>obj_type</attribute-name>
            <value>Director</value>
          </test>
        </condition>
        <numeric-annotation>
          <min>0</min>
        </numeric-annotation>
      </vertex>
      <edge name="acted-in">
        <vertex1>actor</vertex1>
        <vertex2>movie</vertex2>
        <directed>true</directed>
        <condition>
          <test>
            <operator>eq</operator>
            <attribute-name>link_type</attribute-name>
            <value>ActedIn</value>
          </test>
        </condition>
        <numeric-annotation>
          <min>1</min>
        </numeric-annotation>
      </edge>
      <edge name="directed">
        <vertex1>director</vertex1>
        <vertex2>movie</vertex2>
        <directed>true</directed>
        <condition>
          <test>
            <operator>eq</operator>
            <attribute-name>link_type</attribute-name>
            <value>Directed</value>
          </test>
        </condition>
        <numeric-annotation>
          <min>1</min>
        </numeric-annotation>
      </edge>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </subquery>
  </query-body>
  <editor-data>
    <vertex-location name="studio" x="82.0" y="167.0" />
    <vertex-location name="actor" x="504.0" y="33.0" />
    <vertex-location name="movie" x="290.0" y="111.0" />
    <vertex-location name="director" x="502.0" y="223.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Const_DB04_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Const_DB04_Q01">
  <description>Books published before movie release</description>
  <query-body>
    <vertex name="movie">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>movie</value>
        </test>
      </condition>
    </vertex>
    <vertex name="book">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>book</value>
        </test>
      </condition>
    </vertex>
    <edge name="linked-to">
      <vertex1>book</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
    </edge>
    <constraint>
      <and>
        <test>
          <operator>lt</operator>
          <item>
            <item-name>book</item-name>
            <attribute-name>PubDate</attribute-name>
          </item>
          <item>
            <item-name>movie</item-name>
            <attribute-name>ReleaseYear</attribute-name>
          </item>
        </test>
      </and>
    </constraint>
  </query-body>
  <editor-data>
    <vertex-location name="movie" x="442.0" y="132.0" />
    <vertex-location name="book" x="117.0" y="133.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Basics_DB02_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Basics_DB02_Q01">
  <description>Simple three-object query</description>
  <query-body>
    <vertex name="A" />
    <vertex name="B" />
    <vertex name="C" />
    <edge name="X">
      <vertex1>A</vertex1>
      <vertex2>C</vertex2>
      <directed>true</directed>
    </edge>
    <edge name="Y">
      <vertex1>B</vertex1>
      <vertex2>C</vertex2>
      <directed>true</directed>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="A" x="167.0" y="54.0" />
    <vertex-location name="B" x="166.0" y="147.0" />
    <vertex-location name="C" x="328.0" y="110.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB03_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Annot_DB03_Q01">
  <description>Actors with roles in two or more movies</description>
  <query-body>
    <vertex name="actor">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>person</value>
        </test>
      </condition>
    </vertex>
    <vertex name="movie">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>movie</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>2</min>
      </numeric-annotation>
    </vertex>
    <edge name="role">
      <vertex1>actor</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>exists</operator>
          <attribute-name>Role</attribute-name>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="actor" x="73.0" y="66.0" />
    <vertex-location name="movie" x="358.0" y="164.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB05_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Annot_DB05_Q01">
  <description>Books written by someone other than Stephen King</description>
  <query-body>
    <vertex name="author">
      <condition>
        <and>
          <test>
            <operator>eq</operator>
            <attribute-name>ObjType</attribute-name>
            <value>person</value>
          </test>
          <test>
            <operator>ne</operator>
            <attribute-name>Name</attribute-name>
            <value>Stephen King</value>
          </test>
        </and>
      </condition>
    </vertex>
    <vertex name="book">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>book</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <edge name="wrote">
      <vertex1>author</vertex1>
      <vertex2>book</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>LinkType</attribute-name>
          <value>author-of</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="author" x="98.0" y="142.0" />
    <vertex-location name="book" x="413.0" y="271.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/family/data/families/family_2/query_A_B_X1infD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">
<graph-query name="_A_B_X1infD">
    <description>_A_B_X1infD</description>
    <query-body>
        <vertex name="A">
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>objectType</attribute-name>
                    <value>A</value>
                </test>
            </condition>
        </vertex>
        <vertex name="B">
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>objectType</attribute-name>
                    <value>B</value>
                </test>
            </condition>
        </vertex>
        <edge name="X">
            <vertex1>A</vertex1>
            <vertex2>B</vertex2>
            <directed>true</directed>
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>linkType</attribute-name>
                    <value>X</value>
                </test>
            </condition>
            <numeric-annotation>
                <min>1</min>
            </numeric-annotation>
        </edge>
    </query-body>
</graph-query>
