=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/family/data/families/family_4/graph-query.dtd
<!--
$Id: graph-query.dtd 2733 2006-09-11 21:33:59Z schapira $

Part of the open-source Proximity system
(see LICENSE for copyright and license information).

Proximity Graph Query DTD. Does not support the following:
    o updates
    o atomic_constraint -> ... | const_term comp_op const_term
    o cond_term -> ... | agg_op (attr_name) | ...
    o annotation -> [counter_var := annot_limits] | ...
-->


<!-- graph-query -->

<!ELEMENT graph-query (description?, query-body, editor-data?)>
<!ATTLIST graph-query name CDATA #REQUIRED>


<!-- description -->
<!ELEMENT description (#PCDATA)>


<!-- query-body -->

<!ELEMENT query-body (vertex, (edge | vertex)*, subquery*, constraint?, add-link*, cached*)>
<!ELEMENT subquery (vertex, (edge | vertex)*, subquery*, numeric-annotation)>

<!ELEMENT vertex (condition?, numeric-annotation?)>
<!ATTLIST vertex name CDATA #REQUIRED>

<!ELEMENT edge (vertex1, vertex2, directed, condition?, numeric-annotation?)>
<!ATTLIST edge name CDATA #REQUIRED>
<!ELEMENT vertex1 (#PCDATA)>	<!-- NB: direction is FROM 1 TO 2! -->
<!ELEMENT vertex2 (#PCDATA)>
<!ELEMENT directed (#PCDATA)>	<!-- possible values: "true", "false" -->

<!ELEMENT numeric-annotation (min, max?)>	<!-- min and max are whole numbers, and min <= max. valid combinations: [i..j], [i..], or [i] -->
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>


<!ENTITY % dnf "(or | and | not | test)">	<!-- disjunctive normal form -->
<!-- constraints should only test between pairs items
     We use DNF in the DTD for consistency, but in reality only <AND>s can be used in constraints
     also, no constrainsts involving annotated vertices are allowed.
 -->
<!ELEMENT constraint %dnf;>
<!ELEMENT condition %dnf;>		<!-- conditions should only compare attribute names and values, or existence of an attribute name -->

<!ENTITY % and-body "not | test">
<!ELEMENT or (and | %and-body;)+>
<!ELEMENT and (%and-body;)+>
<!ELEMENT not (test)>

<!-- test operands should be consistent:
  for constraints: two edge-names, or two vertex-names
  for conditions - operators:
       "eq", "ge", "le", "ne" : an attribute-name and a value (binary operators), or two items
       "exists"               :  an attribute name (unary operator)
 -->
<!ENTITY % operand "(attribute-name | value | item)">
<!ELEMENT test (operator, %operand;, (%operand;)?)>
<!ELEMENT operator (#PCDATA)>	<!-- possible values: "eq", "ge", "gt", "le", "lt", "ne", "exists" -->
<!ELEMENT attribute-name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT item (item-name, (attribute-name | id))>  <!-- for constraints -->
<!ELEMENT item-name (#PCDATA)>
<!ELEMENT id EMPTY>


<!-- editor-data
This is an optional element that contains information specific to the QGraph
editor (more specifically, vertex layout information). We would have preferred
to save the layout in separate files, but decided such a solution would impose
an undue burden on users.
 -->
<!ELEMENT editor-data (vertex-location+)>

<!ELEMENT vertex-location EMPTY>
<!ATTLIST vertex-location name CDATA #REQUIRED>
<!ATTLIST vertex-location x CDATA #REQUIRED>
<!ATTLIST vertex-location y CDATA #REQUIRED>


<!ELEMENT add-link (vertex1, vertex2)>
<!ATTLIST add-link attrname CDATA #REQUIRED>
<!ATTLIST add-link attrval CDATA #REQUIRED>

<!ELEMENT cached EMPTY >
<!ATTLIST cached item CDATA #REQUIRED>
<!ATTLIST cached container CDATA #REQUIRED>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Basics_DB03_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Basics_DB03_Q01">
  <description>Query using undirected link</description>
  <query-body>
    <vertex name="B" />
    <vertex name="A" />
    <edge name="X">
      <vertex1>A</vertex1>
      <vertex2>B</vertex2>
      <directed>false</directed>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="B" x="392.0" y="106.0" />
    <vertex-location name="A" x="130.0" y="105.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Const_DB05_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Const_DB05_Q01">
  <description>Home pages not linked to other pages on same site</description>
  <query-body>
    <vertex name="start-page">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>PageType</attribute-name>
          <value>home</value>
        </test>
      </condition>
    </vertex>
    <vertex name="linked-page">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>PageType</attribute-name>
          <value>other</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>0</min>
        <max>0</max>
      </numeric-annotation>
    </vertex>
    <edge name="linked-to">
      <vertex1>start-page</vertex1>
      <vertex2>linked-page</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <constraint>
      <and>
        <test>
          <operator>eq</operator>
          <item>
            <item-name>start-page</item-name>
            <attribute-name>Site</attribute-name>
          </item>
          <item>
            <item-name>linked-page</item-name>
            <attribute-name>Site</attribute-name>
          </item>
        </test>
      </and>
    </constraint>
  </query-body>
  <editor-data>
    <vertex-location name="start-page" x="97.0" y="52.0" />
    <vertex-location name="linked-page" x="366.0" y="153.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/tutorial/examples/add-supervises-links.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for
     copyright and license information). -->

<graph-query name="add-supervises-links">
  <description>Adds links from faculty to students when both are linked to the same research project</description>
  <query-body>
    <vertex name="professor">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>pagetype</attribute-name>
          <value>Faculty</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <vertex name="project">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>pagetype</attribute-name>
          <value>ResearchProject</value>
        </test>
      </condition>
    </vertex>
    <vertex name="student">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>pagetype</attribute-name>
          <value>Student</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <edge name="directs">
      <vertex1>professor</vertex1>
      <vertex2>project</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <edge name="has-member">
      <vertex1>project</vertex1>
      <vertex2>student</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <add-link attrname="link_type" attrval="supervises">
      <vertex1>professor</vertex1>
      <vertex2>student</vertex2>
    </add-link>
  </query-body>
  <editor-data>
    <vertex-location name="professor" x="99.0" y="50.0" />
    <vertex-location name="project" x="231.0" y="156.0" />
    <vertex-location name="student" x="385.0" y="66.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Const_DB01_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Const_DB01_Q01">
  <description>One-dimensional cluster query</description>
  <query-body>
    <vertex name="core_page">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>web page</value>
        </test>
      </condition>
    </vertex>
    <vertex name="linked_page">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>web page</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <edge name="link">
      <vertex1>core_page</vertex1>
      <vertex2>linked_page</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="core_page" x="89.0" y="122.0" />
    <vertex-location name="linked_page" x="345.0" y="204.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/datagen2/attributes/iid-coreT-query-test.xml
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<graph-query name="New Query">
    <description>New Editor Query</description>
    <query-body>
        <vertex name="T">
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>objecttype</attribute-name>
                    <value>T</value>
                </test>
            </condition>
        </vertex>
        <edge name="linksFrom">
            <vertex1>S</vertex1>
            <vertex2>T</vertex2>
            <directed>true</directed>
            <numeric-annotation>
                <min>1</min>
            </numeric-annotation>
        </edge>
        <subquery>
            <vertex name="S">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>S</value>
                    </test>
                </condition>
            </vertex>
            <vertex name="linkedT">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>T</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>0</min>
                </numeric-annotation>
            </vertex>
            <edge name="linksTo">
                <vertex1>S</vertex1>
                <vertex2>linkedT</vertex2>
                <directed>true</directed>
                <numeric-annotation>
                    <min>1</min>
                </numeric-annotation>
            </edge>
            <numeric-annotation>
                <min>0</min>
            </numeric-annotation>
        </subquery>
    </query-body>
    <editor-data>
        <vertex-location name="T" x="52" y="150"/>
        <vertex-location name="S" x="338" y="200"/>
        <vertex-location name="linkedT" x="621" y="253"/>
    </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/family/data/families/family_3/query_A_B12_X11RD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">
<graph-query name="_A_B12_X11RD">
    <description>_A_B12_X11RD</description>
    <query-body>
        <vertex name="A">
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>objectType</attribute-name>
                    <value>A</value>
                </test>
            </condition>
        </vertex>
        <vertex name="B">
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>objectType</attribute-name>
                    <value>B</value>
                </test>
            </condition>
            <numeric-annotation>
                <min>1</min>
                <max>2</max>
            </numeric-annotation>
        </vertex>
        <edge name="X">
            <vertex1>B</vertex1>
            <vertex2>A</vertex2>
            <directed>true</directed>
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>linkType</attribute-name>
                    <value>X</value>
                </test>
            </condition>
            <numeric-annotation>
                <min>1</min>
                <max>1</max>
            </numeric-annotation>
        </edge>
    </query-body>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Basics_DB01_Q03.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Basics_DB01_Q03">
  <description>Query using comparison operator</description>
  <query-body>
    <vertex name="A">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>person</value>
        </test>
      </condition>
    </vertex>
    <vertex name="B">
      <condition>
        <test>
          <operator>lt</operator>
          <attribute-name>PubDate</attribute-name>
          <value>1990</value>
        </test>
      </condition>
    </vertex>
    <edge name="X">
      <vertex1>A</vertex1>
      <vertex2>B</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>LinkType</attribute-name>
          <value>author-of</value>
        </test>
      </condition>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="A" x="97.0" y="109.0" />
    <vertex-location name="B" x="365.0" y="109.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/test-query.xml
<!DOCTYPE graph-query SYSTEM "graph-query.dtd"> 

<!--
$Id: test-query.xml 1723 2004-12-09 16:45:43Z cornell $

Part of the open-source Proximity system
  (see LICENSE for copyright and license information).

-->
<graph-query name="Test Query">
    <description>a test query with a valid constraint (starts with AND)</description>
    <query-body>
        <vertex name="vertex1">
        </vertex>
        <edge name="v1-to-v2">
            <vertex1>vertex1</vertex1>
            <vertex2>vertex2</vertex2>
            <directed>true</directed>
            <numeric-annotation>
                <min>1</min>
            </numeric-annotation>
        </edge>
        <vertex name="vertex2">
        </vertex>
        <constraint>
            <and>
                <test>
                    <operator>ne</operator>
                    <item>
                        <item-name>vertex1</item-name>
                        <id/>
                    </item>
                    <item>
                        <item-name>vertex2</item-name>
                        <id/>
                    </item>
                </test>
                <test>
                    <operator>ne</operator>
                    <item>
                        <item-name>vertex2</item-name>
                        <id/>
                    </item>
                    <item>
                        <item-name>vertex1</item-name>
                        <id/>
                    </item>
                </test>
            </and>
        </constraint>
    </query-body>
</graph-query>
