=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/family/data/families/family_4/graph-query.dtd
<!--
$Id: graph-query.dtd 2733 2006-09-11 21:33:59Z schapira $

Part of the open-source Proximity system
(see LICENSE for copyright and license information).

Proximity Graph Query DTD. Does not support the following:
    o updates
    o atomic_constraint -> ... | const_term comp_op const_term
    o cond_term -> ... | agg_op (attr_name) | ...
    o annotation -> [counter_var := annot_limits] | ...
-->


<!-- graph-query -->

<!ELEMENT graph-query (description?, query-body, editor-data?)>
<!ATTLIST graph-query name CDATA #REQUIRED>


<!-- description -->
<!ELEMENT description (#PCDATA)>


<!-- query-body -->

<!ELEMENT query-body (vertex, (edge | vertex)*, subquery*, constraint?, add-link*, cached*)>
<!ELEMENT subquery (vertex, (edge | vertex)*, subquery*, numeric-annotation)>

<!ELEMENT vertex (condition?, numeric-annotation?)>
<!ATTLIST vertex name CDATA #REQUIRED>

<!ELEMENT edge (vertex1, vertex2, directed, condition?, numeric-annotation?)>
<!ATTLIST edge name CDATA #REQUIRED>
<!ELEMENT vertex1 (#PCDATA)>	<!-- NB: direction is FROM 1 TO 2! -->
<!ELEMENT vertex2 (#PCDATA)>
<!ELEMENT directed (#PCDATA)>	<!-- possible values: "true", "false" -->

<!ELEMENT numeric-annotation (min, max?)>	<!-- min and max are whole numbers, and min <= max. valid combinations: [i..j], [i..], or [i] -->
<!ELEMENT min (#PCDATA)>
<!ELEMENT max (#PCDATA)>


<!ENTITY % dnf "(or | and | not | test)">	<!-- disjunctive normal form -->
<!-- constraints should only test between pairs items
     We use DNF in the DTD for consistency, but in reality only <AND>s can be used in constraints
     also, no constrainsts involving annotated vertices are allowed.
 -->
<!ELEMENT constraint %dnf;>
<!ELEMENT condition %dnf;>		<!-- conditions should only compare attribute names and values, or existence of an attribute name -->

<!ENTITY % and-body "not | test">
<!ELEMENT or (and | %and-body;)+>
<!ELEMENT and (%and-body;)+>
<!ELEMENT not (test)>

<!-- test operands should be consistent:
  for constraints: two edge-names, or two vertex-names
  for conditions - operators:
       "eq", "ge", "le", "ne" : an attribute-name and a value (binary operators), or two items
       "exists"               :  an attribute name (unary operator)
 -->
<!ENTITY % operand "(attribute-name | value | item)">
<!ELEMENT test (operator, %operand;, (%operand;)?)>
<!ELEMENT operator (#PCDATA)>	<!-- possible values: "eq", "ge", "gt", "le", "lt", "ne", "exists" -->
<!ELEMENT attribute-name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT item (item-name, (attribute-name | id))>  <!-- for constraints -->
<!ELEMENT item-name (#PCDATA)>
<!ELEMENT id EMPTY>


<!-- editor-data
This is an optional element that contains information specific to the QGraph
editor (more specifically, vertex layout information). We would have preferred
to save the layout in separate files, but decided such a solution would impose
an undue burden on users.
 -->
<!ELEMENT editor-data (vertex-location+)>

<!ELEMENT vertex-location EMPTY>
<!ATTLIST vertex-location name CDATA #REQUIRED>
<!ATTLIST vertex-location x CDATA #REQUIRED>
<!ATTLIST vertex-location y CDATA #REQUIRED>


<!ELEMENT add-link (vertex1, vertex2)>
<!ATTLIST add-link attrname CDATA #REQUIRED>
<!ATTLIST add-link attrval CDATA #REQUIRED>

<!ELEMENT cached EMPTY >
<!ATTLIST cached item CDATA #REQUIRED>
<!ATTLIST cached container CDATA #REQUIRED>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Basics_DB01_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Basics_DB01_Q01">
  <description>Simple two-object query</description>
  <query-body>
    <vertex name="B" />
    <vertex name="A" />
    <edge name="X">
      <vertex1>A</vertex1>
      <vertex2>B</vertex2>
      <directed>true</directed>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="B" x="351.0" y="122.0" />
    <vertex-location name="A" x="161.0" y="121.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB06_Q01.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Annot_DB06_Q01">
  <description>Properly annotated query</description>
  <query-body>
    <vertex name="movie">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>movie</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <vertex name="actor">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>person</value>
        </test>
      </condition>
    </vertex>
    <edge name="role">
      <vertex1>actor</vertex1>
      <vertex2>movie</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>exists</operator>
          <attribute-name>Role</attribute-name>
        </test>
      </condition>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
  </query-body>
  <editor-data>
    <vertex-location name="movie" x="372.0" y="60.0" />
    <vertex-location name="actor" x="103.0" y="139.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/tutorial/examples/different-schools.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="different-schools">
  <description>Finds web pages at one school that link to a page at a different school</description>
  <query-body>
    <vertex name="linked_page">
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </vertex>
    <vertex name="start_page" />
    <edge name="linked_to">
      <vertex1>start_page</vertex1>
      <vertex2>linked_page</vertex2>
      <directed>false</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <constraint>
      <and>
        <test>
          <operator>ne</operator>
          <item>
            <item-name>start_page</item-name>
            <attribute-name>school</attribute-name>
          </item>
          <item>
            <item-name>linked_page</item-name>
            <attribute-name>school</attribute-name>
          </item>
        </test>
      </and>
    </constraint>
  </query-body>
  <editor-data>
    <vertex-location name="linked_page" x="293.0" y="165.0" />
    <vertex-location name="start_page" x="70.0" y="46.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qged/hot100-neighborhood-add-link.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<graph-query name="New Query">
    <description>New Editor Query</description>
    <query-body>
        <vertex name="CoreFile">
            <condition>
                <and>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>File</value>
                    </test>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>hot100</attribute-name>
                        <value>1</value>
                    </test>
                </and>
            </condition>
        </vertex>
        <edge name="afterQuery">
            <vertex1>Query</vertex1>
            <vertex2>CoreFile</vertex2>
            <directed>false</directed>
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>linktype</attribute-name>
                    <value>file_query</value>
                </test>
            </condition>
            <numeric-annotation>
                <min>1</min>
            </numeric-annotation>
        </edge>
        <edge name="ownsFile">
            <vertex1>Owner</vertex1>
            <vertex2>CoreFile</vertex2>
            <directed>true</directed>
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>linktype</attribute-name>
                    <value>owns</value>
                </test>
            </condition>
            <numeric-annotation>
                <min>1</min>
            </numeric-annotation>
        </edge>
        <subquery>
            <vertex name="Co-ownedFile">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>File</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>0</min>
                </numeric-annotation>
            </vertex>
            <vertex name="Owner">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>User</value>
                    </test>
                </condition>
            </vertex>
            <edge name="co-ownsFile">
                <vertex1>Owner</vertex1>
                <vertex2>Co-ownedFile</vertex2>
                <directed>true</directed>
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>linktype</attribute-name>
                        <value>owns</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>1</min>
                </numeric-annotation>
            </edge>
            <numeric-annotation>
                <min>0</min>
            </numeric-annotation>
        </subquery>
        <subquery>
            <vertex name="Co-queriedUser">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>User</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>0</min>
                </numeric-annotation>
            </vertex>
            <vertex name="Co-queriedFile">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>File</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>0</min>
                </numeric-annotation>
            </vertex>
            <vertex name="Query">
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>objecttype</attribute-name>
                        <value>Query</value>
                    </test>
                </condition>
            </vertex>
            <edge name="co-queryFile">
                <vertex1>Query</vertex1>
                <vertex2>Co-queriedFile</vertex2>
                <directed>true</directed>
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>linktype</attribute-name>
                        <value>file_query</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>0</min>
                </numeric-annotation>
            </edge>
            <edge name="co-queryUsers">
                <vertex1>Co-queriedUser</vertex1>
                <vertex2>Query</vertex2>
                <directed>true</directed>
                <condition>
                    <test>
                        <operator>eq</operator>
                        <attribute-name>linktype</attribute-name>
                        <value>makes_query</value>
                    </test>
                </condition>
                <numeric-annotation>
                    <min>1</min>
                </numeric-annotation>
            </edge>
            <numeric-annotation>
                <min>0</min>
            </numeric-annotation>
        </subquery>
        <constraint>
            <and>
                <test>
                    <operator>ne</operator>
                    <item>
                        <item-name>CoreFile</item-name>
                        <id/>
                    </item>
                    <item>
                        <item-name>Co-ownedFile</item-name>
                        <id/>
                    </item>
                </test>
                <test>
                    <operator>ne</operator>
                    <item>
                        <item-name>CoreFile</item-name>
                        <id/>
                    </item>
                    <item>
                        <item-name>Co-queriedFile</item-name>
                        <id/>
                    </item>
                </test>
            </and>
        </constraint>

        <add-link attrname="link_type" attrval="connected">
            <vertex1>CoreFile</vertex1>
            <vertex2>Co-queriedFile</vertex2>
        </add-link>

        <add-link attrname="link_type" attrval="connected again">
            <vertex1>CoreFile</vertex1>
            <vertex2>Co-queriedFile</vertex2>
        </add-link>

    </query-body>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/mult-edge-query.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<graph-query name="Multiple Edge Query">
  <description>a test query with multiple edges and self-loops</description>
  <query-body>
    <vertex name="Vertex1" />
    <vertex name="Vertex2" />
    <vertex name="Vertex3" />
    <edge name="Edge1">
      <vertex1>Vertex1</vertex1>
      <vertex2>Vertex1</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <edge name="Edge2">
      <vertex1>Vertex1</vertex1>
      <vertex2>Vertex2</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <edge name="Edge3">
      <vertex1>Vertex2</vertex1>
      <vertex2>Vertex3</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
    <edge name="Edge4">
      <vertex1>Vertex2</vertex1>
      <vertex2>Vertex3</vertex2>
      <directed>true</directed>
      <numeric-annotation>
        <min>1</min>
      </numeric-annotation>
    </edge>
  </query-body>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Const_DB02_Q02.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<graph-query name="Const_DB02_Q02">
  <description>Genealogy query with inequality constraint</description>
  <query-body>
    <vertex name="child">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>person</value>
        </test>
      </condition>
    </vertex>
    <vertex name="parent1">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>person</value>
        </test>
      </condition>
    </vertex>
    <vertex name="parent2">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>ObjType</attribute-name>
          <value>person</value>
        </test>
      </condition>
    </vertex>
    <edge name="has-parent1">
      <vertex1>child</vertex1>
      <vertex2>parent1</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>LinkType</attribute-name>
          <value>has-parent</value>
        </test>
      </condition>
    </edge>
    <edge name="has-parent2">
      <vertex1>child</vertex1>
      <vertex2>parent2</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>LinkType</attribute-name>
          <value>has-parent</value>
        </test>
      </condition>
    </edge>
    <constraint>
      <and>
        <test>
          <operator>ne</operator>
          <item>
            <item-name>parent1</item-name>
            <id />
          </item>
          <item>
            <item-name>parent2</item-name>
            <id />
          </item>
        </test>
      </and>
    </constraint>
  </query-body>
  <editor-data>
    <vertex-location name="child" x="217.0" y="227.0" />
    <vertex-location name="parent1" x="45.0" y="97.0" />
    <vertex-location name="parent2" x="439.0" y="105.0" />
  </editor-data>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/app/test-param-single-and.qg2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<graph-query name="new query">
    <description>no description</description>
    <query-body>
        <vertex name="Item1">
            <condition>
                <test>
                    <operator>eq</operator>
                    <attribute-name>obj_type</attribute-name>
                    <value>Individual</value>
                </test>
            </condition>
        </vertex>
    </query-body>
</graph-query>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/qgraph2/frequent_coauthor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE graph-query SYSTEM "graph-query.dtd">

<graph-query name="frequent co-authors">
  <description>finds pairs of authors who have co-authored five or more
        times</description>
  <query-body>
    <vertex name="Author2">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>objecttype</attribute-name>
          <value>Author</value>
        </test>
      </condition>
    </vertex>
    <vertex name="Author1">
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>objecttype</attribute-name>
          <value>Author</value>
        </test>
      </condition>
    </vertex>
    <edge name="CoAuthor">
      <vertex1>Author1</vertex1>
      <vertex2>Author2</vertex2>
      <directed>true</directed>
      <condition>
        <test>
          <operator>eq</operator>
          <attribute-name>linktype</attribute-name>
          <value>Co-Authored</value>
        </test>
      </condition>
      <numeric-annotation>
        <min>5</min>
      </numeric-annotation>
    </edge>
  </query-body>
</graph-query>
