=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/resources/prox3db.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

$Id: prox3db.dtd 2038 2005-03-24 21:46:28Z schapira $

Part of the open-source Proximity system
(see LICENSE for copyright and license information).

This is the DTD for Proximity3 Database Export XML.

-->

<!ELEMENT PROX3DB (OBJECTS?, LINKS?, ATTRIBUTES?, CONTAINERS?)>


<!ELEMENT OBJECTS (OBJECT*)>
<!ELEMENT OBJECT EMPTY>
<!ATTLIST OBJECT ID CDATA #REQUIRED>


<!ELEMENT LINKS (LINK*)>
<!ELEMENT LINK EMPTY>
<!ATTLIST LINK
ID CDATA #REQUIRED
O1-ID CDATA #REQUIRED
O2-ID CDATA #REQUIRED
>


<!ELEMENT ATTRIBUTES (ATTRIBUTE*)>
<!ELEMENT ATTRIBUTE (ATTR-VALUE*)>
<!--
    ITEM-TYPE: possible values: "O","L", or "C"
    DATA-TYPE: possible values: see Attributes.defineAttribute()
-->
<!ATTLIST ATTRIBUTE
NAME CDATA #REQUIRED
ITEM-TYPE CDATA #REQUIRED
DATA-TYPE CDATA #REQUIRED
>


<!ELEMENT ATTR-VALUE (COL-VALUE+)>
<!ATTLIST ATTR-VALUE ITEM-ID CDATA #REQUIRED>

<!ELEMENT COL-VALUE (#PCDATA)>


<!ELEMENT CONTAINERS (CONTAINER*)>
<!ELEMENT CONTAINER (SUBG-ITEMS?, SUBG-ATTRIBUTES?, CONTAINER*)>
<!ATTLIST CONTAINER
NAME CDATA #REQUIRED
ID CDATA #REQUIRED
>

<!ELEMENT SUBG-ITEMS (ITEM*)>
<!ELEMENT ITEM EMPTY>
<!-- ITEM-TYPE: possible values: "O" (oh) or "L" -->
<!ATTLIST ITEM
SUBG-ID CDATA #REQUIRED
ITEM-ID CDATA #REQUIRED
ITEM-TYPE CDATA #REQUIRED
NAME CDATA #REQUIRED
>

<!ELEMENT SUBG-ATTRIBUTES (SUBG-ATTRIBUTE*)>
<!ELEMENT SUBG-ATTRIBUTE (ATTR-VALUE*)>
<!--
    DATA-TYPE: possible values: see Attributes.defineAttribute()
-->
<!ATTLIST SUBG-ATTRIBUTE
NAME CDATA #REQUIRED
DATA-TYPE CDATA #REQUIRED
>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB04.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Annot_DB04">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="01" O2-ID="03"/>
        <LINK ID="03" O1-ID="01" O2-ID="04"/>
        <LINK ID="04" O1-ID="02" O2-ID="05"/>
        <LINK ID="05" O1-ID="03" O2-ID="05"/>
        <LINK ID="06" O1-ID="03" O2-ID="05"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Director</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Academy Award</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Ron Howard</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Apollo 13</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>A Beautiful Mind</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Far and Away</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="AwardName" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Best Picture</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="LinkType" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>directed</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>directed</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>directed</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>nominated</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>nominated</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>won</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Const_DB04.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Const_DB04">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
        <OBJECT ID="06"/>
        <OBJECT ID="07"/>
        <OBJECT ID="08"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="03" O2-ID="04"/>
        <LINK ID="03" O1-ID="05" O2-ID="06"/>
        <LINK ID="04" O1-ID="07" O2-ID="08"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                  <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                  <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                  <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                  <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                  <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>Carrie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>Shakespeare in Love</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                  <COL-VALUE>A Beautiful Mind</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                  <COL-VALUE>Bag of Bones</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>Carrie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                  <COL-VALUE>Shakespeare in Love</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                  <COL-VALUE>A Beautiful Mind</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                  <COL-VALUE>Bag of Bones</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="PubDate" ITEM-TYPE="O" DATA-TYPE="INT">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>1974</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>1981</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>1993</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>2003</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>1999</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                  <COL-VALUE>1998</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                  <COL-VALUE>1998</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="ReleaseYear" ITEM-TYPE="O" DATA-TYPE="INT">
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>1976</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                  <COL-VALUE>1998</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                  <COL-VALUE>2001</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Basics_DB04.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Basics_DB04">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="02" O2-ID="02"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>project-page</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>directory-page</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="LinkType" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>link</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>loop</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/app/export-xml-container.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB>
    <CONTAINERS>
        <CONTAINER NAME="b" ID="1">
            <SUBG-ITEMS>
                <ITEM SUBG-ID="0" ITEM-ID="1" ITEM-TYPE="O" NAME="A"/>
                <ITEM SUBG-ID="0" ITEM-ID="1" ITEM-TYPE="L" NAME="X"/>
            </SUBG-ITEMS>
            <SUBG-ATTRIBUTES>
                <SUBG-ATTRIBUTE NAME="attr1" DATA-TYPE="year:int">
                    <ATTR-VALUE ITEM-ID="1">
                        <COL-VALUE>1995</COL-VALUE>
                    </ATTR-VALUE>
                </SUBG-ATTRIBUTE>
            </SUBG-ATTRIBUTES>
        </CONTAINER>
    </CONTAINERS>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/SubQ_DB02.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="SubQ_DB02">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
        <OBJECT ID="06"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="01" O2-ID="03"/>
        <LINK ID="03" O1-ID="03" O2-ID="01"/>
        <LINK ID="04" O1-ID="03" O2-ID="02"/>
        <LINK ID="05" O1-ID="01" O2-ID="04"/>
        <LINK ID="06" O1-ID="04" O2-ID="05"/>
        <LINK ID="07" O1-ID="05" O2-ID="05"/>
        <LINK ID="08" O1-ID="01" O2-ID="06"/>
        <LINK ID="09" O1-ID="06" O2-ID="01"/>
        <LINK ID="10" O1-ID="06" O2-ID="06"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="PageType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Faculty</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Student</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Student</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Faculty</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Student</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>Student</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Page" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>page01.html</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>page02.html</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>page03.html</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>page04.html</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>page05.html</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>page06.html</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Const_DB02.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Const_DB02">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="02" O2-ID="01"/>
        <LINK ID="02" O1-ID="02" O2-ID="03"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Tony Curtis</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Jamie Lee Curtis</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Janet Leigh</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="LinkType" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>has-parent</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>has-parent</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Annot_DB01">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
        <OBJECT ID="06"/>
        <OBJECT ID="07"/>
        <OBJECT ID="08"/>
        <OBJECT ID="09"/>
        <OBJECT ID="10"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="02" O2-ID="01"/>
        <LINK ID="02" O1-ID="03" O2-ID="01"/>
        <LINK ID="03" O1-ID="04" O2-ID="01"/>
        <LINK ID="04" O1-ID="05" O2-ID="01"/>
        <LINK ID="05" O1-ID="06" O2-ID="02"/>
        <LINK ID="06" O1-ID="06" O2-ID="04"/>
        <LINK ID="07" O1-ID="07" O2-ID="04"/>
        <LINK ID="08" O1-ID="08" O2-ID="03"/>
        <LINK ID="09" O1-ID="08" O2-ID="05"/>
        <LINK ID="10" O1-ID="09" O2-ID="05"/>
        <LINK ID="11" O1-ID="10" O2-ID="05"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Academy Award</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="10">
                <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="AwardName" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Best Picture</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Forrest Gump</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Chicago</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Titanic</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Shakespeare in Love</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>Paramount</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>20th Century Fox</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>Miramax</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>Universal</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="10">
                <COL-VALUE>Bedford Falls Productions</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="LinkType" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>won-award</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>won-award</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>won-award</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>won-award</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="10">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="11">
                <COL-VALUE>produced</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/tutorial/examples/more-linktag-values.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="link_tag" ITEM-TYPE="L" DATA-TYPE="str">
            <ATTR-VALUE ITEM-ID="1">
                <COL-VALUE>NEW-VALUE</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="2">
                <COL-VALUE>NEW-VALUE</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="3">
                <COL-VALUE>NEW-VALUE</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="4">
                <COL-VALUE>NEW-VALUE</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="5">
                <COL-VALUE>NEW-VALUE</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>
