=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/resources/prox3db.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

$Id: prox3db.dtd 2038 2005-03-24 21:46:28Z schapira $

Part of the open-source Proximity system
(see LICENSE for copyright and license information).

This is the DTD for Proximity3 Database Export XML.

-->

<!ELEMENT PROX3DB (OBJECTS?, LINKS?, ATTRIBUTES?, CONTAINERS?)>


<!ELEMENT OBJECTS (OBJECT*)>
<!ELEMENT OBJECT EMPTY>
<!ATTLIST OBJECT ID CDATA #REQUIRED>


<!ELEMENT LINKS (LINK*)>
<!ELEMENT LINK EMPTY>
<!ATTLIST LINK
ID CDATA #REQUIRED
O1-ID CDATA #REQUIRED
O2-ID CDATA #REQUIRED
>


<!ELEMENT ATTRIBUTES (ATTRIBUTE*)>
<!ELEMENT ATTRIBUTE (ATTR-VALUE*)>
<!--
    ITEM-TYPE: possible values: "O","L", or "C"
    DATA-TYPE: possible values: see Attributes.defineAttribute()
-->
<!ATTLIST ATTRIBUTE
NAME CDATA #REQUIRED
ITEM-TYPE CDATA #REQUIRED
DATA-TYPE CDATA #REQUIRED
>


<!ELEMENT ATTR-VALUE (COL-VALUE+)>
<!ATTLIST ATTR-VALUE ITEM-ID CDATA #REQUIRED>

<!ELEMENT COL-VALUE (#PCDATA)>


<!ELEMENT CONTAINERS (CONTAINER*)>
<!ELEMENT CONTAINER (SUBG-ITEMS?, SUBG-ATTRIBUTES?, CONTAINER*)>
<!ATTLIST CONTAINER
NAME CDATA #REQUIRED
ID CDATA #REQUIRED
>

<!ELEMENT SUBG-ITEMS (ITEM*)>
<!ELEMENT ITEM EMPTY>
<!-- ITEM-TYPE: possible values: "O" (oh) or "L" -->
<!ATTLIST ITEM
SUBG-ID CDATA #REQUIRED
ITEM-ID CDATA #REQUIRED
ITEM-TYPE CDATA #REQUIRED
NAME CDATA #REQUIRED
>

<!ELEMENT SUBG-ATTRIBUTES (SUBG-ATTRIBUTE*)>
<!ELEMENT SUBG-ATTRIBUTE (ATTR-VALUE*)>
<!--
    DATA-TYPE: possible values: see Attributes.defineAttribute()
-->
<!ATTLIST SUBG-ATTRIBUTE
NAME CDATA #REQUIRED
DATA-TYPE CDATA #REQUIRED
>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/cookbook/examples/DBManip_AttrsFromData_DB.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="DBManip_AttrsFromData_DB">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
        <OBJECT ID="06"/>
        <OBJECT ID="07"/>
        <OBJECT ID="08"/>
        <OBJECT ID="09"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="03" O2-ID="01"/>
        <LINK ID="02" O1-ID="03" O2-ID="02"/>
        <LINK ID="03" O1-ID="04" O2-ID="01"/>
        <LINK ID="04" O1-ID="05" O2-ID="02"/>
        <LINK ID="05" O1-ID="07" O2-ID="06"/>
        <LINK ID="06" O1-ID="08" O2-ID="06"/>
        <LINK ID="07" O1-ID="09" O2-ID="06"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="obj_type" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                  <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                  <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                  <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                  <COL-VALUE>Studio</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                  <COL-VALUE>Director</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                  <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>Donnie Darko</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>I Heart Huckabees</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>20th Century Fox</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                  <COL-VALUE>Jake Gyllenhaal</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                  <COL-VALUE>Lily Tomlin</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                  <COL-VALUE>Princess Bride</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                  <COL-VALUE>MGM</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                  <COL-VALUE>Rob Reiner</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                  <COL-VALUE>Peter Falk</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="link_type" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>Produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>Produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                  <COL-VALUE>Produced</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                  <COL-VALUE>Directed</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/cookbook/examples/DBManip_Aggregation_DB.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="DBManip_Aggregation_DB">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="02" O2-ID="01"/>
        <LINK ID="03" O1-ID="02" O2-ID="03"/>
        <LINK ID="04" O1-ID="03" O2-ID="01"/>
        <LINK ID="05" O1-ID="03" O2-ID="02"/>
        <LINK ID="06" O1-ID="03" O2-ID="03"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="salary" ITEM-TYPE="O" DATA-TYPE="INT">
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>10</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                  <COL-VALUE>20</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>5</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                  <COL-VALUE>7</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>10</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                  <COL-VALUE>10</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/app/export-xml-full-with-container-7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB>
    <OBJECTS>
        <OBJECT ID="1"/>
        <OBJECT ID="2"/>
        <OBJECT ID="3"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="1" O1-ID="1" O2-ID="2"/>
        <LINK ID="2" O1-ID="1" O2-ID="3"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="attr1" ITEM-TYPE="O" DATA-TYPE="year:int,gross:int">
            <ATTR-VALUE ITEM-ID="1">
                <COL-VALUE>1995</COL-VALUE>
                <COL-VALUE>1000</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="2">
                <COL-VALUE>1996</COL-VALUE>
                <COL-VALUE>100</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="attr1" ITEM-TYPE="L" DATA-TYPE="year:int">
            <ATTR-VALUE ITEM-ID="1">
                <COL-VALUE>1995</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="2">
                <COL-VALUE>1996</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="attr1" ITEM-TYPE="C" DATA-TYPE="time:int">
            <ATTR-VALUE ITEM-ID="0">
                <COL-VALUE>1</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="1">
                <COL-VALUE>3</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
    <CONTAINERS>
        <CONTAINER NAME="a" ID="7">
            <SUBG-ITEMS>
                <ITEM SUBG-ID="0" ITEM-ID="1" ITEM-TYPE="O" NAME="A"/>
                <ITEM SUBG-ID="1" ITEM-ID="2" ITEM-TYPE="O" NAME="B"/>
                <ITEM SUBG-ID="2" ITEM-ID="3" ITEM-TYPE="O" NAME="C"/>
                <ITEM SUBG-ID="1" ITEM-ID="1" ITEM-TYPE="L" NAME="X"/>
            </SUBG-ITEMS>
            <SUBG-ATTRIBUTES>
                <SUBG-ATTRIBUTE NAME="attr1" DATA-TYPE="year:int">
                    <ATTR-VALUE ITEM-ID="1">
                        <COL-VALUE>1995</COL-VALUE>
                    </ATTR-VALUE>
                    <ATTR-VALUE ITEM-ID="2">
                        <COL-VALUE>1996</COL-VALUE>
                    </ATTR-VALUE>
                </SUBG-ATTRIBUTE>
            </SUBG-ATTRIBUTES>
            <CONTAINER NAME="b" ID="1">
                <SUBG-ITEMS>
                    <ITEM SUBG-ID="0" ITEM-ID="1" ITEM-TYPE="O" NAME="A"/>
                    <ITEM SUBG-ID="0" ITEM-ID="1" ITEM-TYPE="L" NAME="X"/>
                </SUBG-ITEMS>
                <SUBG-ATTRIBUTES>
                    <SUBG-ATTRIBUTE NAME="attr1" DATA-TYPE="year:int">
                        <ATTR-VALUE ITEM-ID="1">
                            <COL-VALUE>1995</COL-VALUE>
                        </ATTR-VALUE>
                    </SUBG-ATTRIBUTE>
                </SUBG-ATTRIBUTES>
            </CONTAINER>
        </CONTAINER>
        <CONTAINER NAME="c" ID="2"/>
    </CONTAINERS>
</PROX3DB>
