=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/resources/prox3db.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--

$Id: prox3db.dtd 2038 2005-03-24 21:46:28Z schapira $

Part of the open-source Proximity system
(see LICENSE for copyright and license information).

This is the DTD for Proximity3 Database Export XML.

-->

<!ELEMENT PROX3DB (OBJECTS?, LINKS?, ATTRIBUTES?, CONTAINERS?)>


<!ELEMENT OBJECTS (OBJECT*)>
<!ELEMENT OBJECT EMPTY>
<!ATTLIST OBJECT ID CDATA #REQUIRED>


<!ELEMENT LINKS (LINK*)>
<!ELEMENT LINK EMPTY>
<!ATTLIST LINK
ID CDATA #REQUIRED
O1-ID CDATA #REQUIRED
O2-ID CDATA #REQUIRED
>


<!ELEMENT ATTRIBUTES (ATTRIBUTE*)>
<!ELEMENT ATTRIBUTE (ATTR-VALUE*)>
<!--
    ITEM-TYPE: possible values: "O","L", or "C"
    DATA-TYPE: possible values: see Attributes.defineAttribute()
-->
<!ATTLIST ATTRIBUTE
NAME CDATA #REQUIRED
ITEM-TYPE CDATA #REQUIRED
DATA-TYPE CDATA #REQUIRED
>


<!ELEMENT ATTR-VALUE (COL-VALUE+)>
<!ATTLIST ATTR-VALUE ITEM-ID CDATA #REQUIRED>

<!ELEMENT COL-VALUE (#PCDATA)>


<!ELEMENT CONTAINERS (CONTAINER*)>
<!ELEMENT CONTAINER (SUBG-ITEMS?, SUBG-ATTRIBUTES?, CONTAINER*)>
<!ATTLIST CONTAINER
NAME CDATA #REQUIRED
ID CDATA #REQUIRED
>

<!ELEMENT SUBG-ITEMS (ITEM*)>
<!ELEMENT ITEM EMPTY>
<!-- ITEM-TYPE: possible values: "O" (oh) or "L" -->
<!ATTLIST ITEM
SUBG-ID CDATA #REQUIRED
ITEM-ID CDATA #REQUIRED
ITEM-TYPE CDATA #REQUIRED
NAME CDATA #REQUIRED
>

<!ELEMENT SUBG-ATTRIBUTES (SUBG-ATTRIBUTE*)>
<!ELEMENT SUBG-ATTRIBUTE (ATTR-VALUE*)>
<!--
    DATA-TYPE: possible values: see Attributes.defineAttribute()
-->
<!ATTLIST SUBG-ATTRIBUTE
NAME CDATA #REQUIRED
DATA-TYPE CDATA #REQUIRED
>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB06.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Annot_DB06">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="01" O2-ID="03"/>
        <LINK ID="03" O1-ID="01" O2-ID="03"/>
        <LINK ID="04" O1-ID="01" O2-ID="03"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Alec Guiness</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>The Ladykillers</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Kind Hearts and Coronets</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Role" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Professor Marcus</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Lady Agatha</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>The Duke</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Young Ascoyne</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/cookbook/examples/DBManip_ShortcutLinks_DB.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="DBManip_ShortcutLinks_DB">
    <OBJECTS>
        <OBJECT ID="30"/>
        <OBJECT ID="40"/>
        <OBJECT ID="50"/>
        <OBJECT ID="300"/>
        <OBJECT ID="400"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="30" O2-ID="300"/>
        <LINK ID="02" O1-ID="40" O2-ID="300"/>
        <LINK ID="03" O1-ID="30" O2-ID="400"/>
        <LINK ID="04" O1-ID="40" O2-ID="400"/>
        <LINK ID="05" O1-ID="50" O2-ID="400"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="object_type" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="30">
                  <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="40">
                  <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="50">
                  <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="300">
                  <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="400">
                  <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="30">
                  <COL-VALUE>Al Pacino</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="40">
                  <COL-VALUE>John Cazale</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="50">
                  <COL-VALUE>Marlon Brando</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="300">
                  <COL-VALUE>Dog Day Afternoon</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="400">
                  <COL-VALUE>The Godfather</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="link_type" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="1">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="2">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="3">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="4">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="5">
                  <COL-VALUE>ActedIn</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB02.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Annot_DB02">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="02" O2-ID="01"/>
        <LINK ID="02" O1-ID="02" O2-ID="01"/>
        <LINK ID="03" O1-ID="02" O2-ID="01"/>
        <LINK ID="04" O1-ID="02" O2-ID="01"/>
        <LINK ID="05" O1-ID="03" O2-ID="01"/>
        <LINK ID="06" O1-ID="03" O2-ID="01"/>
        <LINK ID="07" O1-ID="04" O2-ID="01"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Actor</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Angels in America</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Meryl Streep</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Justin Kirk</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Al Pacino</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Role" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Ethel Rosenberg</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Hannah Pitt</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>The Rabbi</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>The Angel Australia</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>The Man in the Park</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>Prior Walter</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>Roy Cohn</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Annot_DB03.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Annot_DB03">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
        <OBJECT ID="06"/>
        <OBJECT ID="07"/>
        <OBJECT ID="08"/>
        <OBJECT ID="09"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="03"/>
        <LINK ID="02" O1-ID="01" O2-ID="03"/>
        <LINK ID="03" O1-ID="01" O2-ID="04"/>
        <LINK ID="04" O1-ID="01" O2-ID="05"/>
        <LINK ID="05" O1-ID="01" O2-ID="05"/>
        <LINK ID="06" O1-ID="01" O2-ID="06"/>
        <LINK ID="07" O1-ID="02" O2-ID="06"/>
        <LINK ID="08" O1-ID="02" O2-ID="07"/>
        <LINK ID="09" O1-ID="02" O2-ID="07"/>
        <LINK ID="10" O1-ID="02" O2-ID="07"/>
        <LINK ID="11" O1-ID="08" O2-ID="07"/>
        <LINK ID="12" O1-ID="08" O2-ID="07"/>
        <LINK ID="13" O1-ID="09" O2-ID="03"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Peter Sellers</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Alec Guiness</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>Dennis Price</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>George C. Scott</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Dr. Strangelove</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>The Pink Panther</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>The Mouse That Roared</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>The Ladykillers</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>Kind Hearts and Coronets</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Role" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Dr. Strangelove</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>President Muffley</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Inspector Clousseau</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Grand Duchess Gloriana</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Tully Bascombe</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>Harry</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>Professor Marcus</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>Lady Agatha</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>The Duke</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="10">
                <COL-VALUE>Young Ascoyne</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="11">
                <COL-VALUE>Duke Louis Mazzini</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="12">
                <COL-VALUE>Mazzini, Sr.</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="13">
                <COL-VALUE>Gen. Buck Turgidson</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/SubQ_DB03.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="SubQ_DB03">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
        <OBJECT ID="06"/>
        <OBJECT ID="07"/>
        <OBJECT ID="08"/>
        <OBJECT ID="09"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="02" O2-ID="01"/>
        <LINK ID="03" O1-ID="01" O2-ID="03"/>
        <LINK ID="04" O1-ID="03" O2-ID="01"/>
        <LINK ID="05" O1-ID="03" O2-ID="04"/>
        <LINK ID="06" O1-ID="04" O2-ID="03"/>
        <LINK ID="07" O1-ID="03" O2-ID="05"/>
        <LINK ID="08" O1-ID="05" O2-ID="03"/>
        <LINK ID="09" O1-ID="01" O2-ID="06"/>
        <LINK ID="10" O1-ID="06" O2-ID="01"/>
        <LINK ID="11" O1-ID="06" O2-ID="07"/>
        <LINK ID="12" O1-ID="07" O2-ID="06"/>
        <LINK ID="13" O1-ID="06" O2-ID="08"/>
        <LINK ID="14" O1-ID="08" O2-ID="06"/>
        <LINK ID="15" O1-ID="08" O2-ID="09"/>
        <LINK ID="16" O1-ID="09" O2-ID="08"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Kevin Bacon</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Sean Penn</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Jack Nicholson</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Pierce Brosnan</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Connie Ray</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="06">
                <COL-VALUE>Tom Hanks</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="07">
                <COL-VALUE>Michael Clarke Duncan</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="08">
                <COL-VALUE>Denzel Washington</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="09">
                <COL-VALUE>Cissy Houston</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/app/export-xml-attribute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="attr1" ITEM-TYPE="O" DATA-TYPE="year:int,gross:int">
            <ATTR-VALUE ITEM-ID="1">
                <COL-VALUE>1995</COL-VALUE>
                <COL-VALUE>1000</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="2">
                <COL-VALUE>1996</COL-VALUE>
                <COL-VALUE>100</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Cond_DB01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Cond_DB01">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="02"/>
        <LINK ID="02" O1-ID="01" O2-ID="03"/>
        <LINK ID="03" O1-ID="01" O2-ID="04"/>
        <LINK ID="04" O1-ID="01" O2-ID="05"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>person</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>book</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Ed McBain</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>The Fruminous Bandersnatch</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Alice in Jeopardy</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Vanishing Ladies</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>The Moment She Was Gone</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="LinkType" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>author-of</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>author-of</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>author-of</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>author-of</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="WrittenAs" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Richard Marsten</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Evan Hunter</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/doc/user/qgraph/examples/Cond_DB02.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Part of the open-source Proximity system (see LICENSE for 
     copyright and license information). -->

<!DOCTYPE PROX3DB SYSTEM "prox3db.dtd">
<PROX3DB NAME="Cond_DB02">
    <OBJECTS>
        <OBJECT ID="01"/>
        <OBJECT ID="02"/>
        <OBJECT ID="03"/>
        <OBJECT ID="04"/>
        <OBJECT ID="05"/>
    </OBJECTS>
    <LINKS>
        <LINK ID="01" O1-ID="01" O2-ID="03"/>
        <LINK ID="02" O1-ID="01" O2-ID="05"/>
        <LINK ID="03" O1-ID="01" O2-ID="04"/>
        <LINK ID="04" O1-ID="02" O2-ID="04"/>
        <LINK ID="05" O1-ID="02" O2-ID="05"/>
    </LINKS>
    <ATTRIBUTES>
        <ATTRIBUTE NAME="ObjType" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>actor</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>movie</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Name" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Graham Chapman</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Peter Cook</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Title" ITEM-TYPE="O" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Monty Python and the Holy Grail</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>Jake's Journey</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Yellowbeard</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="LinkType" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>acted-in</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>acted-in</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>acted-in</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>acted-in</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>acted-in</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
        <ATTRIBUTE NAME="Role" ITEM-TYPE="L" DATA-TYPE="STR">
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>King Arthur</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Voice of God</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Middle Head</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="01">
                <COL-VALUE>Hiccoughing Guard</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="02">
                <COL-VALUE>Captain Yellowbeard</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Sir George</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="03">
                <COL-VALUE>Queen</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="04">
                <COL-VALUE>King Arthur</COL-VALUE>
            </ATTR-VALUE>
            <ATTR-VALUE ITEM-ID="05">
                <COL-VALUE>Lord Lambourn</COL-VALUE>
            </ATTR-VALUE>
        </ATTRIBUTE>
    </ATTRIBUTES>
</PROX3DB>
