=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/resources/rbc2.dtd
<!--

  Proximity Relational Bayesian Classifier (RBC) DTD
  Version: 2.0

  Part of the open-source Proximity system
  (see LICENSE for copyright and license information).

  -->

<!-- rpt -->

<!ELEMENT rbc2 (estimator-class, class-label, sources)>

<!-- estimator -->
<!ELEMENT estimator-class (#PCDATA)>

<!-- class label -->
<!ELEMENT class-label (source, class-label-distr)>

<!-- sources -->
<!ELEMENT sources (source-element*)>
<!ELEMENT source-element (source, conditional-distr)>
<!ELEMENT conditional-distr (conditional-distr-info)*>
<!ELEMENT conditional-distr-info (label, class-label-distr)>
<!ELEMENT label (#PCDATA)>

<!-- source NOTE: MUST BE IN SYNCH WITH THE SOURCE ELEMENT IN RPT2.DTD! -->
<!ELEMENT source (source-class, data-type, is-continuous, is-single-value, source-elements) >
<!ELEMENT source-class (#PCDATA)>
<!ELEMENT data-type (#PCDATA)>
<!ELEMENT is-continuous (#PCDATA)>
<!ELEMENT is-single-value (#PCDATA)>
<!ELEMENT source-elements ( (item-name)?, (attr-name)?, (temporal-col)? , (from)?, (to)?, (interval-min)?, (interval-max)?, (core-time-source)?, (related-time-source)?) >
<!ELEMENT item-name (#PCDATA)>
<!ELEMENT attr-name (#PCDATA)>
<!ELEMENT interval-min (#PCDATA)>
<!ELEMENT interval-max (#PCDATA)>
<!ELEMENT temporal-col (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT core-time-source ( (item-name)?, (attr-name)?) >
<!ELEMENT related-time-source ( (item-name)?, (attr-name)?) >

<!-- class-label-distributions : MUST BE IN SYNCH WITH THE CLASS-LABEL-DISTR ELEMENT IN RPT2.DTD! -->
<!ELEMENT class-label-distr (distr-class, (class-label-info)*) >
<!ELEMENT distr-class (#PCDATA)>
<!ELEMENT class-label-info (#PCDATA) >
<!ATTLIST class-label-info class CDATA #REQUIRED>
<!ATTLIST class-label-info count CDATA #REQUIRED>

=== rpplayground/our-papers/random-regress/old-versions/ILP14/journal-revision/proximity/test/java/kdl/prox/model2/rbc/rbc-test.xml
<!DOCTYPE rbc2 SYSTEM "rbc2.dtd">
<!-- Created by Proximity -->

<rbc2>
  <estimator-class>kdl.prox.model2.rbc.estimators.MultinomialEstimator</estimator-class>
  <class-label>
    <source>
      <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
      <data-type>str</data-type>
      <is-continuous>false</is-continuous>
      <is-single-value>true</is-single-value>
      <source-elements>
        <item-name>core</item-name>
        <attr-name>coreAttr1</attr-name>
      </source-elements>
    </source>
    <class-label-distr>
      <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
      <class-label-info class="+" count="3.0" />
      <class-label-info class="-" count="3.0" />
    </class-label-distr>
  </class-label>
  <sources>
    <source-element>
      <source>
        <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
        <data-type>str</data-type>
        <is-continuous>false</is-continuous>
        <is-single-value>false</is-single-value>
        <source-elements>
          <item-name>relation</item-name>
          <attr-name>relAttr1</attr-name>
        </source-elements>
      </source>
      <conditional-distr>
        <conditional-distr-info>
          <label>+</label>
          <class-label-distr>
            <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
            <class-label-info class="N" count="3.0" />
          </class-label-distr>
        </conditional-distr-info>
        <conditional-distr-info>
          <label>-</label>
          <class-label-distr>
            <distr-class>kdl.prox.model2.common.probdistributions.DiscreteProbDistribution</distr-class>
            <class-label-info class="N" count="1.0" />
            <class-label-info class="Y" count="1.0" />
          </class-label-distr>
        </conditional-distr-info>
      </conditional-distr>
    </source-element>
    <source-element>
      <source>
        <source-class>kdl.prox.model2.common.sources.AttributeSource</source-class>
        <data-type>dbl</data-type>
        <is-continuous>true</is-continuous>
        <is-single-value>false</is-single-value>
        <source-elements>
          <item-name>peripheral</item-name>
          <attr-name>perAttr1</attr-name>
        </source-elements>
      </source>
      <conditional-distr>
        <conditional-distr-info>
          <label>+</label>
          <class-label-distr>
            <distr-class>kdl.prox.model2.common.probdistributions.ContinuousProbDistribution</distr-class>
            <class-label-info class="0.009999999776482582" count="1.0" />
            <class-label-info class="0.30000001192092896" count="1.0" />
            <class-label-info class="0.5" count="1.0" />
            <class-label-info class="0.6000000238418579" count="1.0" />
            <class-label-info class="0.699999988079071" count="1.0" />
          </class-label-distr>
        </conditional-distr-info>
      </conditional-distr>
    </source-element>
  </sources>
</rbc2>
